### ISSUE TITLE
No way to enable firewall

### ISSUE THREAD

**Issue by iler** [meafmira/terraform-provider-upcloud#7]
There seems to be no way to enable firewall. You can add firewall rules but you can't enable the firewall itself.

**Comment by meafmira** [comment]
@iler how can I enable firewall? Didn't find this in api docs

**Comment by iler** [comment]
@meafmira you can do it via the server request https://www.upcloud.com/api/8-servers/#modify-server

**Comment by iler** [comment]
This does not work. If I set the value to `true` firewall does not get enabled and if I set the value to `on` it gives you an error because it's not boolean value. In our API documentation it says that accepted values are `on` and `off`.
